<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosAplicacionSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            // ─── AGROQUÍMICOS: Insecticidas ───────────────────────────────────────────
            ['nombre' => 'ACROBAT',          'ingrediente_activo' => 'Dimetomorf + Pyraclostrobin',         'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'ALLECTUS 150',     'ingrediente_activo' => 'Bifentrina + Imidacloprid',           'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'SPALIMUS',         'ingrediente_activo' => 'Spinetoram',                          'marca' => 'CORTEVA',                'tipo' => 'agroquimico'],
            ['nombre' => 'KOMARL',           'ingrediente_activo' => 'Lambda Cyhalotrina',                  'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'RIMON 100',        'ingrediente_activo' => 'Novaluron',                           'marca' => 'ADAMA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'MATADOR 20',       'ingrediente_activo' => 'Metomilo',                            'marca' => 'ADAMA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'OBERON',           'ingrediente_activo' => 'Spiromesifeno',                       'marca' => 'BAYER',                  'tipo' => 'agroquimico'],
            ['nombre' => 'ETICUS',           'ingrediente_activo' => 'Benzoato de Emamectina',              'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'DECEL',            'ingrediente_activo' => 'Deltametrina',                        'marca' => 'BAYER',                  'tipo' => 'agroquimico'],
            ['nombre' => 'RIMON FAST',       'ingrediente_activo' => 'Novaluron + Imidacloprid',            'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'AMPLIO',           'ingrediente_activo' => 'Clorantraniliprol + Lambda Cyhalotrina', 'marca' => 'SYNGENTA',            'tipo' => 'agroquimico'],
            ['nombre' => 'BELT 480',         'ingrediente_activo' => 'Flubendiamida',                       'marca' => 'BAYER',                  'tipo' => 'agroquimico'],
            ['nombre' => 'ZABRA',            'ingrediente_activo' => 'Permetrina',                          'marca' => 'ALLISTER',               'tipo' => 'agroquimico'],
            ['nombre' => 'CORAGEN',          'ingrediente_activo' => 'Clorantraniliprol',                   'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'GLOXDOWN',         'ingrediente_activo' => 'Indoxicarb',                          'marca' => 'VERSA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'SURPASS',          'ingrediente_activo' => 'Carbosulfan',                         'marca' => 'VALENT',                 'tipo' => 'agroquimico'],
            ['nombre' => 'MASSADA MAX',      'ingrediente_activo' => 'Novaluron + Zetacipermetrina',        'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'SEVIN 80',         'ingrediente_activo' => 'Carbaril',                            'marca' => 'IMASA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'FENTROX',          'ingrediente_activo' => 'Fenitrothion',                        'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'POUNCE',           'ingrediente_activo' => 'Permetrina',                          'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'RINGO',            'ingrediente_activo' => 'Benzoato de Emamectina',              'marca' => 'VERSA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'MUSTANG MAX',      'ingrediente_activo' => 'Zetacipermetrina',                    'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'MURIELLA MAX',     'ingrediente_activo' => 'Imidacloprid + Flupyradifurona',      'marca' => 'BAYER',                  'tipo' => 'agroquimico'],
            ['nombre' => 'KNOCK OUT',        'ingrediente_activo' => 'Potasio (insecticida)',                'marca' => 'JCO',                    'tipo' => 'agroquimico'],
            ['nombre' => 'ENGEO',            'ingrediente_activo' => 'Tiametoxam + Lambda Cyhalotrina',     'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'CARONTE',          'ingrediente_activo' => 'Diflubenzuron',                       'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'UNIKEM',           'ingrediente_activo' => 'Tiametoxam',                          'marca' => 'UPL',                    'tipo' => 'agroquimico'],
            ['nombre' => 'FLY KILL',         'ingrediente_activo' => 'Ácido Graso',                         'marca' => 'FARFAX',                 'tipo' => 'agroquimico'],
            ['nombre' => 'TORRITTO',         'ingrediente_activo' => 'Adiflumetopim',                       'marca' => 'CORTEVA',                'tipo' => 'agroquimico'],
            ['nombre' => 'JITSU',            'ingrediente_activo' => 'Lambda Cyhalotrina',                  'marca' => 'LINEA PLATINUM',         'tipo' => 'agroquimico'],
            ['nombre' => 'ATAMBA',           'ingrediente_activo' => 'Lambda Cyhalotrina',                  'marca' => 'PLATINUM',               'tipo' => 'agroquimico'],
            ['nombre' => 'STOREBI',          'ingrediente_activo' => 'Carbendazim + Abamectina',            'marca' => 'PLATINUM',               'tipo' => 'agroquimico'],
            ['nombre' => 'KORITE',           'ingrediente_activo' => 'Lambda Cyhalotrina',                  'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'COFENGRID',        'ingrediente_activo' => 'Imidacloprid',                        'marca' => 'AGROTERIUM',             'tipo' => 'agroquimico'],
            ['nombre' => 'MANSIDA 100',      'ingrediente_activo' => 'Novaluron',                           'marca' => 'FNC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'HA SET',           'ingrediente_activo' => 'Lambda Cyhalotrina',                  'marca' => 'FNC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'ACTARA',           'ingrediente_activo' => 'Tiametoxam',                          'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'VERONA',           'ingrediente_activo' => 'Tiametoxam',                          'marca' => 'VERSA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'BINDAR',           'ingrediente_activo' => 'Bifentrina',                          'marca' => 'AGROMOL',                'tipo' => 'agroquimico'],
            ['nombre' => 'MENOPAL',          'ingrediente_activo' => 'Monocrotofos',                        'marca' => 'AGROMOL',                'tipo' => 'agroquimico'],
            ['nombre' => 'NANOSFOS',         'ingrediente_activo' => 'Clorpirifos',                         'marca' => 'AGROMOL',                'tipo' => 'agroquimico'],
            ['nombre' => 'HEMIFIPLATA',      'ingrediente_activo' => 'Bifenthrin + Clorpirimifos',          'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'TALSTAR',          'ingrediente_activo' => 'Bifentrina',                          'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'SUNPICX',          'ingrediente_activo' => 'Bifentrina',                          'marca' => 'FMC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'PROTECTIN',        'ingrediente_activo' => 'Abamectina',                          'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'BT WORM',          'ingrediente_activo' => 'Bacillus thuringiensis',              'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'CLARION',          'ingrediente_activo' => 'Benzoato de Emamectina',              'marca' => 'ALBALIK',                'tipo' => 'agroquimico'],
            ['nombre' => 'CAPTAIN',          'ingrediente_activo' => null,                                   'marca' => 'ADAMA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'FIDATO',           'ingrediente_activo' => 'Acefato + Ciflutrina',                'marca' => 'DOW AGROSCIENCES',       'tipo' => 'agroquimico'],
            ['nombre' => 'ORETHENE ULTRA',   'ingrediente_activo' => 'Acefato',                             'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'DUSAM',            'ingrediente_activo' => 'Clorpirifos',                         'marca' => 'URL',                    'tipo' => 'agroquimico'],

            // ─── AGROQUÍMICOS: Fungicidas ─────────────────────────────────────────────
            ['nombre' => 'MAXTROBIN',        'ingrediente_activo' => 'Tebuconazole + Azoxistrobina',        'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'CONOVY',           'ingrediente_activo' => 'Trifloxistrobina',                    'marca' => 'BASF',                   'tipo' => 'agroquimico'],
            ['nombre' => 'AVONE',            'ingrediente_activo' => 'Tiofanato Metilo',                    'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'OLIST',            'ingrediente_activo' => 'Azoxistrobina + Propiconazol',        'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'VIPSIL',           'ingrediente_activo' => 'Fluoxastrobina',                      'marca' => 'ARISTA',                 'tipo' => 'agroquimico'],
            ['nombre' => 'FINAL BACTER',     'ingrediente_activo' => 'Oxitetraciclina',                     'marca' => 'GROWIN',                 'tipo' => 'agroquimico'],
            ['nombre' => 'FOXTIVA FE',       'ingrediente_activo' => 'Trichoderma',                         'marca' => 'CANES',                  'tipo' => 'agroquimico'],
            ['nombre' => 'PEA MAX',          'ingrediente_activo' => 'Trichoderma',                         'marca' => 'CANES',                  'tipo' => 'agroquimico'],
            ['nombre' => 'METRATE',          'ingrediente_activo' => 'Metrafenona',                         'marca' => 'FNC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'CELESTE 720',      'ingrediente_activo' => 'Fludioxonil + Tiametoxam',            'marca' => 'ADAMA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'NATRU',            'ingrediente_activo' => 'Kasugamicina',                        'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'BLACK JP',         'ingrediente_activo' => 'Trifloxistrobina',                    'marca' => null,                     'tipo' => 'agroquimico'],
            ['nombre' => 'ACCORD 60',        'ingrediente_activo' => 'Cymoxanil',                           'marca' => 'SULFATEC',               'tipo' => 'agroquimico'],
            ['nombre' => 'CHAN DP',          'ingrediente_activo' => 'Carbonato de Cobre',                  'marca' => 'LQC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'MANZATE PRO STRIKE','ingrediente_activo' => 'Mancozeb',                           'marca' => 'AGRISOLVER',             'tipo' => 'agroquimico'],
            ['nombre' => 'TEGEXAS',          'ingrediente_activo' => 'Pyraclostrobin',                      'marca' => 'BASF',                   'tipo' => 'agroquimico'],
            ['nombre' => 'MERGENT',          'ingrediente_activo' => 'Procloraz',                           'marca' => 'FNC',                    'tipo' => 'agroquimico'],
            ['nombre' => 'SIMON',            'ingrediente_activo' => 'Tebuconazol',                         'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'BAATI',            'ingrediente_activo' => 'Prodiofenamo',                        'marca' => null,                     'tipo' => 'agroquimico'],
            ['nombre' => 'SKY ROLÁN',        'ingrediente_activo' => 'Azoxistrobina',                       'marca' => 'AGROMOL',                'tipo' => 'agroquimico'],
            ['nombre' => 'RIDOMIL BRAVO',    'ingrediente_activo' => 'Metalaxil-M + Clorotalonil',          'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'SCORE 250CE',      'ingrediente_activo' => 'Difenoconazol',                       'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'RALLY 40W',        'ingrediente_activo' => 'Myclobutanil',                        'marca' => 'CORTEVA',                'tipo' => 'agroquimico'],
            ['nombre' => 'FANDAMIN',         'ingrediente_activo' => 'Fludioxonil + Cymoxanil',             'marca' => 'ARYSTA',                 'tipo' => 'agroquimico'],
            ['nombre' => 'CAPRO',            'ingrediente_activo' => 'Captan',                              'marca' => 'ADAMA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'PREMAT',           'ingrediente_activo' => 'Metam Sodio',                         'marca' => 'ARYSTA',                 'tipo' => 'agroquimico'],
            ['nombre' => 'SULPHURAGNOL',     'ingrediente_activo' => 'Azufre',                              'marca' => null,                     'tipo' => 'agroquimico'],

            // ─── AGROQUÍMICOS: Herbicidas ─────────────────────────────────────────────
            ['nombre' => 'GESAPRIM',         'ingrediente_activo' => 'Atrazina',                            'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'MALATHION 1000',   'ingrediente_activo' => 'Malatión',                            'marca' => 'PLATINUM',               'tipo' => 'agroquimico'],
            ['nombre' => 'ANTORCHA',         'ingrediente_activo' => 'Paraquat',                            'marca' => 'DRAGON',                 'tipo' => 'agroquimico'],
            ['nombre' => 'CODRAZ',           'ingrediente_activo' => 'Trifloxisulfuron + Dicamba',          'marca' => 'BASF',                   'tipo' => 'agroquimico'],
            ['nombre' => 'GACAPRIM',         'ingrediente_activo' => 'Atrazina',                            'marca' => 'SYNGENTA',               'tipo' => 'agroquimico'],
            ['nombre' => 'PLEO',             'ingrediente_activo' => 'Piridato',                            'marca' => 'VALENT',                 'tipo' => 'agroquimico'],
            ['nombre' => 'TRIFLUR',          'ingrediente_activo' => 'Trifluralina',                        'marca' => 'HELM',                   'tipo' => 'agroquimico'],
            ['nombre' => 'SEMOA',            'ingrediente_activo' => 'Halosulfuron',                        'marca' => 'GOWAN',                  'tipo' => 'agroquimico'],
            ['nombre' => 'FAENA',            'ingrediente_activo' => 'Glifosato',                           'marca' => 'MONSANTO',               'tipo' => 'agroquimico'],
            ['nombre' => 'UNIMARK',          'ingrediente_activo' => 'Pendimetalina',                       'marca' => 'UPL',                    'tipo' => 'agroquimico'],
            ['nombre' => 'TROCIN 2N',        'ingrediente_activo' => 'Prometrina',                          'marca' => 'AGRISTAR',               'tipo' => 'agroquimico'],
            ['nombre' => 'PEXA',             'ingrediente_activo' => 'Dicamba + Prosulfuron',               'marca' => null,                     'tipo' => 'agroquimico'],

            // ─── AGROQUÍMICOS: Adherentes / Coadyuvantes ─────────────────────────────
            ['nombre' => 'XTENDER',          'ingrediente_activo' => 'Adherente',                           'marca' => 'FIASA',                  'tipo' => 'agroquimico'],
            ['nombre' => 'INEX-A',           'ingrediente_activo' => 'Adherente',                           'marca' => 'COSMOSEL',               'tipo' => 'agroquimico'],
            ['nombre' => 'NEW COVER',        'ingrediente_activo' => 'Adherente',                           'marca' => 'ALTIARA',                'tipo' => 'agroquimico'],
            ['nombre' => 'RTZO PRAY',        'ingrediente_activo' => 'Adherente',                           'marca' => 'AGROMOL',                'tipo' => 'agroquimico'],
            ['nombre' => 'SIROP MIX',        'ingrediente_activo' => 'Coadyuvante',                         'marca' => 'ZGM',                    'tipo' => 'agroquimico'],
            ['nombre' => 'RIOXPRAINTEGRUM',  'ingrediente_activo' => 'Coadyuvante',                         'marca' => 'UPL',                    'tipo' => 'agroquimico'],
            ['nombre' => 'FACILITY',         'ingrediente_activo' => 'Oxatiapiprolin',                      'marca' => 'CORTEVA',                'tipo' => 'agroquimico'],
            ['nombre' => 'DELIVERY',         'ingrediente_activo' => 'Coadyuvante',                         'marca' => 'ALTIARA',                'tipo' => 'agroquimico'],
            ['nombre' => 'AGRIBAT',          'ingrediente_activo' => 'Macroelementos',                      'marca' => 'ARVENSIS',               'tipo' => 'agroquimico'],

            // ─── FERTILIZANTES: NPK y macroelementos ─────────────────────────────────
            ['nombre' => 'ZINC FLOW',        'ingrediente_activo' => 'Zinc',                                'marca' => 'DRAGON',                 'tipo' => 'fertilizante'],
            ['nombre' => 'MECOP N-P-K MICROS','ingrediente_activo' => 'Nitrógeno, Fósforo, Potasio y Micros','marca' => 'ARROSI',              'tipo' => 'fertilizante'],
            ['nombre' => 'CODAFOL 14-6-5',   'ingrediente_activo' => 'N-P-K',                              'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'UREA',             'ingrediente_activo' => 'Nitrógeno',                           'marca' => 'AARFS',                  'tipo' => 'fertilizante'],
            ['nombre' => 'ALAN 22',          'ingrediente_activo' => 'Nitrógeno',                           'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'KNOCKOUT (Potasio)','ingrediente_activo' => 'Potasio',                            'marca' => 'JCO',                    'tipo' => 'fertilizante'],
            ['nombre' => 'PRIMELIFE',        'ingrediente_activo' => 'Potasio',                             'marca' => 'PRIMELIFE',              'tipo' => 'fertilizante'],
            ['nombre' => 'SEQUIFOL BMO',     'ingrediente_activo' => 'Boro + Molibdeno',                   'marca' => 'SEIPASA',                'tipo' => 'fertilizante'],
            ['nombre' => 'TRIPLE 19',        'ingrediente_activo' => 'NPK 19-19-19',                        'marca' => 'HAIFA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'MAP',              'ingrediente_activo' => 'Fosfato Monoamónico 12-61',           'marca' => 'GREEN HOUSE',            'tipo' => 'fertilizante'],
            ['nombre' => 'NITRATO DE MAGNESIO','ingrediente_activo' => 'Magnesio',                          'marca' => 'GREENBOW',               'tipo' => 'fertilizante'],
            ['nombre' => 'NITRATO DE POTASIO GH','ingrediente_activo' => 'Potasio',                        'marca' => 'GREEN HOUSE',            'tipo' => 'fertilizante'],
            ['nombre' => 'NITRATO DE POTASIO CANES','ingrediente_activo' => 'Potasio',                     'marca' => 'CANES',                  'tipo' => 'fertilizante'],
            ['nombre' => 'OPO',              'ingrediente_activo' => 'Fósforo',                             'marca' => 'JCO',                    'tipo' => 'fertilizante'],
            ['nombre' => 'CODAFOSNITROGEN',  'ingrediente_activo' => 'Nitrógeno',                           'marca' => 'FIASA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'NITRATO DE CALCIO','ingrediente_activo' => 'Calcio',                              'marca' => 'GREENYHOW',              'tipo' => 'fertilizante'],
            ['nombre' => 'SULFATO DE MAGNESIO','ingrediente_activo' => 'Magnesio + Azufre',                 'marca' => 'GREENSHOW',              'tipo' => 'fertilizante'],
            ['nombre' => 'ACIDO FOSFORICO',  'ingrediente_activo' => 'Ácido Fosfórico',                    'marca' => 'IMPULSORA',              'tipo' => 'fertilizante'],
            ['nombre' => 'RAGREEN',          'ingrediente_activo' => 'Potasio + Fósforo',                  'marca' => 'IMPULSORA',              'tipo' => 'fertilizante'],
            ['nombre' => 'GAS AMONICO',      'ingrediente_activo' => 'Amoniaco',                            'marca' => 'IMPULSORA',              'tipo' => 'fertilizante'],
            ['nombre' => 'FOSFORTATO',       'ingrediente_activo' => 'Nitrógeno',                           'marca' => 'GREEN HOUSE',            'tipo' => 'fertilizante'],
            ['nombre' => 'MASTER SOIL',      'ingrediente_activo' => 'Mejorador de suelo',                 'marca' => 'FIASA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'SULFATO DE MAGNESIO CANES','ingrediente_activo' => 'Magnesio',                   'marca' => 'CANES',                  'tipo' => 'fertilizante'],
            ['nombre' => 'CODA CA BORO',     'ingrediente_activo' => 'Calcio + Boro',                      'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'CODA SILI',        'ingrediente_activo' => 'Sílice + Boro',                      'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'MICROBORO',        'ingrediente_activo' => 'Boro',                                'marca' => 'CANES',                  'tipo' => 'fertilizante'],
            ['nombre' => 'MAXI BORO',        'ingrediente_activo' => 'Boro',                                'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'HA QUER PTZA',     'ingrediente_activo' => 'Potasio',                             'marca' => 'FIASA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'QUER FO',          'ingrediente_activo' => 'Microelementos',                      'marca' => 'QUINKAIL',               'tipo' => 'fertilizante'],
            ['nombre' => 'IMIRUN',           'ingrediente_activo' => 'Carbono, Fósforo, Zinc, Hierro, Potasio','marca' => 'FIASA',              'tipo' => 'fertilizante'],
            ['nombre' => 'QUELATO MANGANESO','ingrediente_activo' => 'Manganeso EDTA',                      'marca' => null,                     'tipo' => 'fertilizante'],
            ['nombre' => 'AGROMIL FLUID',    'ingrediente_activo' => 'NPK foliar',                          'marca' => 'AGROENZIMAS',            'tipo' => 'fertilizante'],
            ['nombre' => 'AGROPLEX BMO',     'ingrediente_activo' => 'Boro + Molibdeno',                   'marca' => 'AGROENZIMAS',            'tipo' => 'fertilizante'],
            ['nombre' => 'SOLUMAX',          'ingrediente_activo' => 'Potasio + Fósforo + Microelementos', 'marca' => 'FIASA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'CITMAGNIO ZN',     'ingrediente_activo' => 'Magnesio + Zinc',                    'marca' => 'GRUNDAG',                'tipo' => 'fertilizante'],
            ['nombre' => 'GRUNDAG 127',      'ingrediente_activo' => 'Ácido Hidroxietilidendifosfénico',    'marca' => 'GRUNDAG',                'tipo' => 'fertilizante'],
            ['nombre' => 'NUMANTE',          'ingrediente_activo' => 'Hierro, Magnesio, Zinc',              'marca' => null,                     'tipo' => 'fertilizante'],
            ['nombre' => 'JUNIPERAX',        'ingrediente_activo' => 'Hierro + Zinc',                      'marca' => 'AGROENZIMAS',            'tipo' => 'fertilizante'],
            ['nombre' => 'ISONOFER',         'ingrediente_activo' => 'Hierro quelado',                      'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'PLATA (Micros)',   'ingrediente_activo' => 'N + K + Micros',                     'marca' => 'IASEO',                  'tipo' => 'fertilizante'],

            // ─── FERTILIZANTES: Bioestimulantes, Aminoácidos, Algas ─────────────────
            ['nombre' => 'KELPO',            'ingrediente_activo' => 'Extracto de algas marinas',          'marca' => 'ORGANDMOS',              'tipo' => 'fertilizante'],
            ['nombre' => 'BAYCOLAN',         'ingrediente_activo' => 'Microelementos',                     'marca' => 'BAYER',                  'tipo' => 'fertilizante'],
            ['nombre' => 'FIAMIN FOL',       'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'FIASA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'DALGIN',           'ingrediente_activo' => 'Algas marinas',                       'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'KINETICS',         'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'SEIPASA',                'tipo' => 'fertilizante'],
            ['nombre' => 'BIOCOMBI',         'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'ALTIARA',                'tipo' => 'fertilizante'],
            ['nombre' => 'VEL2ME PLUS',      'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'ALTIARA',                'tipo' => 'fertilizante'],
            ['nombre' => 'HORMOLAT',         'ingrediente_activo' => 'Hormonas vegetales',                  'marca' => 'ALTIARA',                'tipo' => 'fertilizante'],
            ['nombre' => 'YARA VITA MAIZE BOOTS','ingrediente_activo' => 'Fertilizante foliar',            'marca' => 'YARA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'YARA VITA OPTITRAC','ingrediente_activo' => 'Bioestimulante foliar',              'marca' => 'YARA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'YARA VITA ZIRAC',  'ingrediente_activo' => 'Nitrógeno + Zinc',                   'marca' => 'YARA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'YARA VITA BORTRAC','ingrediente_activo' => 'Boro + Nitrógeno',                   'marca' => 'YARA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'PRIMER IMPULSO',   'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'GREENFLUIRT',            'tipo' => 'fertilizante'],
            ['nombre' => 'G+ CRECIMIO',      'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'GREENFLUIRT',            'tipo' => 'fertilizante'],
            ['nombre' => 'G+ CRECIENDO',     'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'GREENFLUIRT',            'tipo' => 'fertilizante'],
            ['nombre' => 'PRODUCTIN',        'ingrediente_activo' => 'Aminoácidos',                         'marca' => 'GREENFLUIRT',            'tipo' => 'fertilizante'],
            ['nombre' => 'GF-FRUTO LLENO',   'ingrediente_activo' => 'Fertilizante foliar',                'marca' => 'GREEN FORCE',            'tipo' => 'fertilizante'],
            ['nombre' => 'SILUZE',           'ingrediente_activo' => 'Fertilizante foliar',                'marca' => 'GREEN FORCE',            'tipo' => 'fertilizante'],
            ['nombre' => 'CODAHUMUS',        'ingrediente_activo' => 'Ácidos húmicos',                     'marca' => 'CODA',                   'tipo' => 'fertilizante'],
            ['nombre' => 'BTARGUS',          'ingrediente_activo' => 'Bacillus subtilis',                   'marca' => 'RIZO BACTER',            'tipo' => 'fertilizante'],
            ['nombre' => 'STARGOS',          'ingrediente_activo' => 'Bacillus subtilis',                   'marca' => 'RIZO',                   'tipo' => 'fertilizante'],
            ['nombre' => 'BP KORON',         'ingrediente_activo' => 'Enraizador biológico',                'marca' => 'BIOPRODUCTOS AGRICOLA',  'tipo' => 'fertilizante'],
            ['nombre' => 'BIOXPIREN',        'ingrediente_activo' => 'Bioestimulante',                      'marca' => 'UPL',                    'tipo' => 'fertilizante'],
            ['nombre' => 'BIOXPIREN TS',     'ingrediente_activo' => 'Bioestimulante',                      'marca' => 'UPL',                    'tipo' => 'fertilizante'],
            ['nombre' => 'CRECILANT',        'ingrediente_activo' => 'Nutrientes foliares',                 'marca' => 'QUIMA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'MICROBIOR',        'ingrediente_activo' => 'Bacillus',                            'marca' => 'QUIMA',                  'tipo' => 'fertilizante'],
            ['nombre' => 'ROTTING',          'ingrediente_activo' => 'Aminoácidos, Vitaminas, Citocininas, Fósforo','marca' => 'ADAMA',          'tipo' => 'fertilizante'],
            ['nombre' => 'CLARION FOL',      'ingrediente_activo' => 'Aminoácidos + Microelementos',        'marca' => 'ALTIARA',                'tipo' => 'fertilizante'],
        ];

        $now = now();

        // Insertar solo si no existe ya (por nombre + marca)
        foreach ($productos as $p) {
            DB::table('productos_aplicacion')->updateOrInsert(
                ['nombre' => $p['nombre'], 'marca' => $p['marca']],
                [
                    'ingrediente_activo' => $p['ingrediente_activo'],
                    'tipo'               => $p['tipo'],
                    'activo'             => true,
                    'created_at'         => $now,
                    'updated_at'         => $now,
                ]
            );
        }

        $this->command->info('✓ ' . count($productos) . ' productos de aplicación registrados.');
    }
}
